In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer # frequency based DTM
from sklearn.feature_extraction.text import TfidfVectorizer # tf-idf based DTM

In [ ]:
TEXT = ['banana apple apple eggplant',
        'orange carrot banana eggplant',
        'apple carrot banana banana',
        'orange banana grape'
]

# CountVectorizer 이용하기

In [ ]:
tf_vectorizer = CountVectorizer(min_df=1, ngram_range=(1,1))
tf_features = tf_vectorizer.fit_transform(TEXT)

In [ ]:
tf_features

<4x6 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [ ]:
features = np.array(tf_features.todense())
features

array([[2, 1, 0, 1, 0, 0],
       [0, 1, 1, 1, 0, 1],
       [1, 2, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 1]], dtype=int64)

In [ ]:
features

array([[2, 1, 0, 1, 0, 0],
       [0, 1, 1, 1, 0, 1],
       [1, 2, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 1]], dtype=int64)

In [ ]:
features[0]

array([2, 1, 0, 1, 0, 0], dtype=int64)

In [ ]:
features[1]

array([0, 1, 1, 1, 0, 1], dtype=int64)

In [ ]:
np.linalg.norm(features[1]-features[0])

2.449489742783178

In [ ]:
np.linalg.norm(features[1]-features[2])

2.0

In [ ]:
feature_names = tf_vectorizer.get_feature_names()
feature_names

['apple', 'banana', 'carrot', 'eggplant', 'grape', 'orange']

In [ ]:
import pandas as pd
df = pd.DataFrame(data=features, columns=feature_names)
print(df)

   apple  banana  carrot  eggplant  grape  orange
0      2       1       0         1      0       0
1      0       1       1         1      0       1
2      1       2       1         0      0       0
3      0       1       0         0      1       1


# TfidfVectorizer 이용하기

In [ ]:
tfidf_vectorizer = TfidfVectorizer(min_df=1, ngram_range=(1,1))
tfidf_features = tfidf_vectorizer.fit_transform(TEXT)

In [ ]:
tfidf_features = np.array(tfidf_features.todense())
tfidf_features

array([[0.85764287, 0.28383251, 0.        , 0.42882143, 0.        ,
        0.        ],
       [0.        , 0.35696573, 0.53931298, 0.53931298, 0.        ,
        0.53931298],
       [0.51623315, 0.68337886, 0.51623315, 0.        , 0.        ,
        0.        ],
       [0.        , 0.37919167, 0.        , 0.        , 0.72664149,
        0.5728925 ]])

In [ ]:
tfidf_features[0]

array([0.85764287, 0.28383251, 0.        , 0.42882143, 0.        ,
       0.        ])