In [ ]:
import numpy as np # numpy를 사용해서 벡터와 행렬 생성

In [ ]:
a = np.array([1,2])
b = np.array([2,2])
c = np.array([-3, -3]) # array()를 이용하는 경우는 보통 리스트를 인자로 입력

In [ ]:
a

array([1, 2])

# 거리 구하기

In [ ]:
np.linalg.norm(a)

2.23606797749979

In [ ]:
np.linalg.norm(b)

2.8284271247461903

In [ ]:
print(np.linalg.norm(b-a))
print(np.linalg.norm(c-a))

1.0
6.4031242374328485


In [ ]:
dp1 = np.array([30,1])
dp2 = np.array([33,2])
dp3 = np.array([55,25])

In [ ]:
print(np.linalg.norm(dp2-dp1))
print(np.linalg.norm(dp3-dp1))

3.1622776601683795
34.655446902326915


# Cosine similarity

In [ ]:
a

array([1, 2])

In [ ]:
b

array([2, 2])

In [ ]:
np.dot(a,b)

6

In [ ]:
np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

0.9486832980505138

In [ ]:
c

array([-3, -3])

In [ ]:
np.dot(a,c)/(np.linalg.norm(a)*np.linalg.norm(c))

-0.9486832980505138

In [ ]:
doc1 = np.array([2,1,0,0,0,1])
doc2 = np.array([1,0,2,1,0,0])
doc3 = np.array([0,1,0,0,1,2])

In [ ]:
print(np.linalg.norm(doc2-doc1))
print(np.linalg.norm(doc3-doc1))

2.8284271247461903
2.449489742783178


In [ ]:
print(np.dot(doc1,doc2)/(np.linalg.norm(doc1)*np.linalg.norm(doc2)))
print(np.dot(doc1,doc3)/(np.linalg.norm(doc1)*np.linalg.norm(doc3)))

0.33333333333333337
0.5000000000000001
