
![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/330px-NumPy_logo_2020.svg.png)

# 01. 넘파이 기초

학습 목표

- Numpy 배열의 기본 개념을 이해합니다.
- 1차원, 2차원, 3차원 배열을 만들 수 있습니다.
- 인덱싱과 슬라이싱으로 원하는 데이터를 조회할 수 있습니다.
- 배열 사이의 기본적인 연산을 수행할 수 있습니다.

## 1.라이브러리 불러오기

- Numpy 배열을 사용하려면 우선 **numpy** 라이브러리를 불러와야 합니다.
- numpy 라이브러리는 일반적으로 **np** 별칭을 붙여 불러옵니다.

In [ ]:
# 라이브러리 불러오기
import numpy as np

## 2.배열 만들기

- 편의를 위해 **Numpy 배열**을 그냥 **배열**이라고 부르기로 합시다.
- 이후 데이터 처리시 배열로 변환해 연산을 하거나, 결과가 배열로 표시되는 경우가 있습니다.
- 배열에 대한 개념은 정확히 파악해 두기를 권고합니다.

### 2.1.용어 정의

<img src='https://raw.githubusercontent.com/Jangrae/img/master/array.png' width=300 align="left"/>

**[용어]**
- axis: 배열의 각 축
- rank: 축의 개수
- shape: 축의 길이, 배열의 크기

  
**[3 x 4 배열의 경우]**
- axis 0 과 axis 1 을 갖는 2차원 배열
- rank 2 array
- shape는 (3, 4)

### 2.2.배열 만들기

- **np.array() 함수**를 사용해서 배열을 만듭니다.
- 대부분 **리스트**로부터 배열을 만들거나, 머신러닝 관련 함수 결괏값이 배열이 됩니다.

#### 2.2.1.배열 만들기

**1) 1차원 배열 만들기**

In [ ]:
# 1차원 리스트
a1 = [1, 2, 3, 4, 5]

# 배열로 변환
b1 = np.array(a1)

# 확인
print(b1)

[1 2 3 4 5]


**2) 2차원 배열 만들기**

In [ ]:
# 2차원 리스트
# a2 = [[1.5, 2.5, 3.2], [4.2, 5.7, 6.4]]
a2 = [[1.5, 2.5, 3.2],
      [4.2, 5.7, 6.4]]

# 배열로 변환
b2 = np.array(a2)

# 확인
print(b2)

[[1.5 2.5 3.2]
 [4.2 5.7 6.4]]


**3) 3차원 배열 만들기**

In [ ]:
# 3차원 리스트
# a3 = [[[1, 3, 1], [4, 7, 6], [8, 3, 4]], [[6, 2, 4], [8, 1, 5], [3, 5, 9]]]
a3 = [[[1, 3, 1],
       [4, 7, 6],
       [8, 3, 4]],
      [[6, 2, 4],
       [8, 1, 5],
       [3, 5, 9]]]

# 배열로 변환
b3 = np.array(a3)

# 확인
print(b3)

[[[1 3 1]
  [4 7 6]
  [8 3 4]]

 [[6 2 4]
  [8 1 5]
  [3 5 9]]]


#### 2.2.2.배열 정보 확인

- 배열 정보를 확인하는 다음 속성들을 기억하시기 바랍니다.
- 특히 shape 속성은 이후에도 많이 사용될 것입니다.

<img src='https://github.com/DA4BAM/image/blob/main/1,2,3%20%EC%B0%A8%EC%9B%90.png?raw=true' width=800 align="left"/>

**1) 차원 확인**

- ndim 속성으로 배열 차원을 확인합니다.

In [ ]:
# 차원 확인
print(b1.ndim)
print(b2.ndim)
print(b3.ndim)

1
2
3


**2) 형태(크기) 확인**

- shape 속성으로 배열 형태를 확인합니다.
- 결과는 다음과 같은 형태의 튜플로 표시됩니다.
    - 1차원: (x, )
    - 2차원: (x, y)
    - 3차원: (x, y, z)
- 앞에서 부터 axis 0, axis 1, axis 2의 크기를 의미합니다.

In [ ]:
# 형태(크기) 확인
print(b1.shape)
print(b2.shape)
print(b3.shape)

(5,)
(2, 3)
(2, 3, 3)


<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] numpy 라이브러리를 np 별칭을 주어 불러오세요.

In [ ]:
# 라이브러리 불러오기
import numpy as np

[문2] 다음에 주어진 데이터를 갖는 1차원 배열 a1을 만든 후 ndim, shape, dtype을 확인해 보세요.

In [ ]:
# 10, 11, 12, 13, 14, 15

# 배열 만들기
a1 = np.array([10, 11, 12, 13, 14, 15])

# 확인
print(a1)

# 정보 확인
print(a1.ndim)
print(a1.shape)
print(a1.dtype)

[10 11 12 13 14 15]
1
(6,)
int32


[문3] 다음에 주어진 리스트를 요소로 갖는 2차원 배열 a2를 만든 후 ndim, shape, dtype을 확인해 보세요

In [ ]:
a = [[11, 12, 13, 14],
     [15, 16, 17, 18],
     [19, 20, 21, 22]]

# 배열 만들기
a2 = np.array(a)

# 확인
print(a2)

# 정보 확인
print(a2.ndim)
print(a2.shape)
print(a2.dtype)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
2
(3, 4)
int32


## 3.배열 연산

- 배열 사이의 더하기, 빼기, 곱하기, 나누기 등은 이해하기 쉽습니다.
- 하지만 행렬 곱, 행렬 합등의 연산은 악갼의 수학적 지식이 필요합니다.
- 행렬 연산은 선형 대수를 위한 것이므로 설명을 생략합니다.

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4%EC%97%B0%EC%82%B0.png?raw=true' width=600 align="left"/>

In [ ]:
# 두 개의 (2, 2) 형태의 2차원 배열 만들기
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# 확인
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


**1) 배열 더하기**

- \+ 또는 **np.add()** 함수를 사용합니다.

In [ ]:
# 배열 더하기
print(x + y)

# 또는
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


**2) 배열 뺴기**

- \- 또는 **np.subtract()** 함수를 사용합니다.

In [ ]:
# 배열 빼기
print(x - y)

# 또는
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


**3) 배열 곱하기**

- \* 또는 **np.multiply()** 함수를 사용합니다.

In [ ]:
# 배열 곱하기
print(x * y)

# 또는
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


**4) 배열 나누기**

- \/ 또는 **np.divide()** 함수를 사용합니다.

In [ ]:
# 배열 나누기
print(x / y)

# 또는
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


**5) 배열 제곱**

- \** 또는 **np.power()** 함수를 사용합니다.

In [ ]:
# 배열 y 제곱
print(x ** y)

# 또는
print(np.power(x, y))

[[    1    64]
 [ 2187 65536]]
[[    1    64]
 [ 2187 65536]]


In [ ]:
# 배열 제곱
print(x ** 2)

[[ 1  4]
 [ 9 16]]


**6) 배열 집계**

- np.sum(), 혹은 array.sum()
    * axis = 0 : 열 기준 집계
    * axis = 1 : 행 기준 집계
    * 생략하면 : 전체 집계
- 동일한 형태로 사용 가능한 함수 : np.max(), np.min, np.mean(), np.std()

In [ ]:
# array를 생성합니다.
a = np.array([[1,5,7],[2,3,8]])
print(a)

[[1 5 7]
 [2 3 8]]


In [ ]:
# 전체 집계
print(np.sum(a))

# 열기준 집계
print(np.sum(a, axis = 0))

# 행기준 집계
print(np.sum(a, axis = 1))

26
[ 3  8 15]
[13 13]


* 조건에 따른 결과 지정 : np.where(조건문, 참일때 값, 거짓일때 값)

In [ ]:
a = np.array([1,3,2,7])
print(np.where(a> 2, 1, 0))

[0 1 0 1]


## 4.종합실습

1) numpy 라이브러리를 np 별칭을 주어 불러오세요.

In [ ]:
# numpy 라이브러리 불러오기
import numpy as np

2) 다음 형태를 갖는 2차원 배열을 만들어 np_arr 변수로 선언하세요.

In [ ]:
# [[  1  2  3]
#  [  4  5  6]
#  [  7  8  9]
#  [ 10 11 12]]

# 배열 만들기
np_arr = np.array([[  1,  2,  3],
                   [  4,  5,  6],
                   [  7,  8,  9],
                   [ 10, 11, 12]])

# 확인
print(np_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


3) shape 속성을 사용해 np_arr 배열의 행과 열의 크기를 확인하세요.

In [ ]:
# 배열 크기 확인
np_arr.shape

(4, 3)

4) np_arr 배열의 모든 요소에 10을 곱한 결과를 조회하세요.
* np_arr 배열의 실제 값은 바꾸지 않고 10을 곱한 결과를 출력만 합니다

In [ ]:
# print 함수 안에서 np_arr 배열에 10을 곱합니다.
print(np_arr * 10)
print()
# np_arr 배열 확인하기
print(np_arr)
print()
# 배열 원본 데이터에 10배를 곱하고 확인합니다.
np_arr = np_arr *10
print(np_arr)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


10) np_arr 배열의 요소들 중에서 2의 배수는 1, 아니면 0인 배열 a를 만들고 조회하시오.

In [ ]:
a = np.where(np_arr %2== 0, 1, 0)
print(a)

[[0 1 0]
 [1 0 1]
 [0 1 1]
 [1 1 1]]
